/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package visitor_ufu;

import org.junit.jupiter.api.Test;
import visitor_ufu.numberElement.NumberElement;
import visitor_ufu.numberElement.ThreeElement;
import visitor_ufu.numberElement.TwoElement;
import visitor_ufu.visitors.MultiplyVisitor;
import visitor_ufu.visitors.SumMultiplyVisitor;
import visitor_ufu.visitors.SumVisitor;
import visitor_ufu.visitors.TotalSumVisitor;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

class VisitorTest {
    @Test
    void testTotalSumVisitor() {
        TwoElement two1 = new TwoElement(3, 3);
        TwoElement two2 = new TwoElement(2, 7);
        ThreeElement three = new ThreeElement(3, 4, 5);

        List<NumberElement> numberElementList = new ArrayList<>();
        numberElementList.add(two1);
        numberElementList.add(two2);
        numberElementList.add(three);
        System.out.println("Visiting element list with SumVisitor");
        new SumVisitor().visit(numberElementList);

        System.out.println("\nVisiting element list with TotalSumVisitor");
        TotalSumVisitor visitor = new TotalSumVisitor();
        visitor.visit(numberElementList);

        assertEquals(27, visitor.getTotalSum());
    }


    @Test
    void testTotalMultiplyVisitor() {
        TwoElement two1 = new TwoElement(3, 3);
        TwoElement two2 = new TwoElement(2, 7);
        ThreeElement three = new ThreeElement(3, 4, 5);

        List<NumberElement> numberElementList = new ArrayList<>();
        numberElementList.add(two1);
        numberElementList.add(two2);
        numberElementList.add(three);

        System.out.println("\nVisiting element list with MultiplyVisitor");
        new MultiplyVisitor().visit(numberElementList);

        SumMultiplyVisitor visitor = new SumMultiplyVisitor();
        visitor.visit(numberElementList);

        assertEquals(83, visitor.getTotalSum());
    }
}
